### ISSUE TITLE
Travis CI build is breaking with Python 3.4

### ISSUE THREAD

**Issue by mtougeron** [boto/boto#3011]
It looks like Python 3.4 builds on Travis CI are breaking.

**Comment by danielgtaylor** [comment]
It does look that way. Seems to have started after #2985 was merged in, which is rather strange.

**Comment by mtougeron** [comment]
Looks odd to me too. Perhaps it is something with the test-region timing out?

**Comment by jamesls** [comment]
Taking a look.

**Comment by jamesls** [comment]
Looks like it's because httpretty, a test dep we use for mocking out some of the http calls: https://github.com/gabrielfalcao/HTTPretty/issues/228

Our requirements has an unbounded version dependency on this: 

httpretty>=0.7.0

Guessing if I roll back to Latest-1 version, we should get the travis builds back up and running.

**Comment by jamesls** [comment]
Closing, this has been fixed for a while.
