### ISSUE TITLE
Boto can't access cross-account SQS queues

### ISSUE THREAD

**Issue by ikoniaris** [boto/boto#3112]
If there is an SQS queue in AWS account A and a resource-based policy is applied to it to give access to an IAM user/role from AWS account B, then boto can't be used to interact with the queue. Because SQS queue names are not universally unique (like S3 bucket names), boto will try to find the queue in the specified region *in the AWS Account whose credentials are used*, i.e. it will try to find the queue in account B in this case and not account A where it really exists. There is currently no way to specify the Account. I'd suggest to maybe use an ARN instead of just the queue name or something of that effect?

**Comment by pauloubuntu** [comment]
Hi @ikoniaris, 

That's a very tricky approach, I've faced a similar situation a few days ago. It turns out that AWS provides an API that supports only retrieving queues by name and not by the ARN as we'd expect. In another hand, we must agree that sharing SQS queues across multiple accounts isn't something you see every day, so I don't think they will add it very soon.

Here is a link that list all SQS methods available: http://docs.aws.amazon.com/cli/latest/reference/sqs/index.html

Perhaps it should be wiser if you post it on some sort of AWS forum which AWS developers read before they decide which changes they will implement because at my point of view this isn't a boto's issue but an API scenario that hasn't been covered yet.

**Comment by pauloubuntu** [comment]
I've also checked other AWS SDK out and it seems they don't have a method for getting queues by ARN also.

**Comment by pauloubuntu** [comment]
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClient.html

**Comment by pauloubuntu** [comment]
http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.Sqs.SqsClient.html#_getQueueUrl

**Comment by ikoniaris** [comment]
Thanks for looking into this @pauloubuntu. It seems to be an AWS thing, yes.

**Comment by pauloubuntu** [comment]
Hi @ikoniaris 

I've found out a way to access a cross-account SQS resource using boto. It turns out that the solution is a little obvious but neither you nor me had managed to get this working. So, I've decided to write a little tutorial to help further boto users out when they get to this issue.

1 - Let's picture we have two accounts
- account A - Id: 111111111111
- account B - Id: 999999999999

2 - On account A:
- create a queue named : THE-CROSS-ACCOUNT-QUEUE
- add permission to account B to whatever permission you think your application needs

![screen shot 2015-05-02 at 12 16 04 am](https://cloud.githubusercontent.com/assets/1011868/7439813/39eba474-f063-11e4-99a9-934af77ba0b2.png)
![screen shot 2015-05-02 at 12 16 48 am](https://cloud.githubusercontent.com/assets/1011868/7439815/3ce45e0a-f063-11e4-9445-768c77e76979.png)

3 - Using boto with account B credentials

```Python
import boto.sqs

conn = boto.sqs.connect_to_region("us-west-2")
queue = conn.get_queue('THE-CROSS-ACCOUNT-QUEUE', owner_acct_id='111111111111')

print queue.get_attributes()
```

![screen shot 2015-05-02 at 12 17 58 am](https://cloud.githubusercontent.com/assets/1011868/7439822/81258954-f063-11e4-8533-c46ab52ad95d.png)


Let me know if that worked for you. If so, please consider closing this issue.

Cheers

**Comment by ikoniaris** [comment]
That makes sense @PauloMigAlmeida, using the `owner_acct_id` it seems to work. Thanks for looking into this! :+1:

**Comment by alvaro562003** [comment]
it works for me. Thanks
