### ISSUE TITLE
TypeError populating keys from metadata server

### ISSUE THREAD

**Issue by lrowe** [boto/boto#3378]
In my server logs I'm seeing what looks like a rerun of #1907 with boto 2.38.0.

```
    conn = boto.connect_s3()
  File "/srv/encoded/eggs/boto-2.38.0-py3.4.egg/boto/__init__.py", line 141, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/srv/encoded/eggs/boto-2.38.0-py3.4.egg/boto/s3/connection.py", line 190, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/srv/encoded/eggs/boto-2.38.0-py3.4.egg/boto/connection.py", line 555, in __init__
    profile_name)
  File "/srv/encoded/eggs/boto-2.38.0-py3.4.egg/boto/provider.py", line 200, in __init__
    self.get_credentials(access_key, secret_key, security_token, profile_name)
  File "/srv/encoded/eggs/boto-2.38.0-py3.4.egg/boto/provider.py", line 376, in get_credentials
    self._populate_keys_from_metadata_server()
  File "/srv/encoded/eggs/boto-2.38.0-py3.4.egg/boto/provider.py", line 395, in _populate_keys_from_metadata_server
    self._access_key = security['AccessKeyId']
TypeError: string indices must be integers
```

**Comment by jamesls** [comment]
Tried to repro using 2.39.0.  Also tried on python3.4.  Not seeing this issue.  IIRC #1907 was a regression that immediately broke the instance metadata credential retriever.   It doesn't look like this is the same case.

Some additional data that would help:

* How frequently are you seeing this issue
* Is this code running immediately when the instance starts up?

**Comment by lrowe** [comment]
Seems to be happening only intermittently. On this instance which has been up for 10 days I see the same error logged at these times:
```
[Tue Feb 02 19:53:59.009887 2016]
[Wed Feb 03 19:05:34.216450 2016]
[Thu Feb 04 14:07:11.609744 2016]
[Thu Feb 04 14:07:11.609974 2016]
[Thu Feb 04 14:07:19.278424 2016]
[Thu Feb 04 18:03:41.861965 2016]
[Thu Feb 04 18:03:47.638778 2016]
[Thu Feb 04 18:03:52.541109 2016]
[Thu Feb 04 18:03:55.567427 2016]
[Thu Feb 04 18:04:24.094672 2016]
[Thu Feb 04 18:04:33.907620 2016]
[Thu Feb 04 18:04:41.790302 2016]
[Thu Feb 04 18:04:48.464800 2016]
[Thu Feb 04 18:05:02.140420 2016]
[Thu Feb 04 18:05:06.421956 2016]
[Thu Feb 04 18:05:07.461871 2016]
[Thu Feb 04 18:05:10.061933 2016]
[Thu Feb 04 18:06:19.965862 2016]
```
Give the value is a string, it looks to me that this branch of LazyLoadMetadata is getting hit: https://github.com/boto/boto/blob/2.39.0/boto/utils.py#L289

```
                    val = boto.utils.retry_url(
                        self._url + urllib.parse.quote(resource,
                                                       safe="/:"),
                        num_retries=self._num_retries,
                        timeout=self._timeout)
                    if val and val[0] == '{':
                        val = json.loads(val)
                        break
                    else:   # Hits this branch so val is not decoded as a json dict
                        p = val.find('\n')
                        if p > 0:
                            val = val.split('\n')  # Does not hit this branch as val is a string not a list
                        break
```

**Comment by jamesls** [comment]
That certainly seems to be the case.  That would suggest that when we try to retrieve credentials from the instance metadata service, we're occasionally not actually getting back what we expect.

I'm thinking the best course of action would be to add retries to the `_populate_keys_from_metadata_server` if we don't get back a dictionary type we expect.

**Comment by jamesls** [comment]
Looking into the code more, I'm really curious what that string actually is.  I wonder if it's an empty string.  There's a couple places in `retry_url` where it will return an empty string on error:

* https://github.com/boto/boto/blob/develop/boto/utils.py#L221
* https://github.com/boto/boto/blob/develop/boto/utils.py#L230

So what may be happening:

* retry_url is encountering an error.  After enough retries it will return an empty string.
* This is triggering the `else` clause you linked above.
* As a result, the `provider.py` module will try to access the return value as if it were a dictionary, resulting in the `TypeError`.

Are you setting metadata [retry/num_attempts](http://boto.readthedocs.org/en/latest/boto_config_tut.html)?  If not, that can help with this issue.

I think how this is fixed depends on two cases:

1. If this is failing because we're catching an exception and just returning an empty string, then we need to raise a much more clear error message, with steps on how to increase retry attempts.
2. If we're actually getting a 200 OK response from instance metadata that contains text that is not JSON, then we need to count that as a failed attempt and retry again.

I think we have to fix the first case before knowing whether or not we need to fix the second case.  I don't really see a good way to disambiguate the two cases in the code right now.

So for now, I'd suggest just fixing (1).  Seem reasonable? cc @kyleknap  @rayluo @JordonPhillips

**Comment by kyleknap** [comment]
Yeah lets do that for now.

**Comment by Riprock** [comment]
This is effecting me pretty badly. Will this be in 2.40.0? Do we know when that will be? Couldn't find a schedule in contributing guide.
