### ISSUE TITLE
How to push my changes to boto?

### ISSUE THREAD

**Issue by ferozed** [boto/boto#3477]
I have a documentation chanage to propose for the kinesis apis. I have the change on my branch, but I cannot push it up to GITHub. I am getting an access denied error:

--
$ git push -u origin feroze/fix_doc
ERROR: Permission to boto/boto.git denied to ferozed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
--

What is the process for requesting Write access to this project?

Thanks.

**Comment by PauloMigAlmeida** [comment]
hi @ferozed 

You don't have write permissions to boto and it's very likely that you won't, lol. For contributing you should fork boto repository to your account and then open a Pull Request. After Amazon's team confirm that everything is working fine and agree that this is a good improvement to the project they will merge it to the official boto code.

Best Regards

**Comment by ferozed** [comment]
I am doing something similar. I cloned the repo to my account, and created a new branch off develop. Then I committed to that branch, and want to push my new branch here.

so you are saying that this is not supported?

**Comment by PauloMigAlmeida** [comment]
Actually you've cloned boto's repository to you local directory, not to your account. Since you don't have write permissions on this repository you won't be able to push the changes you made so far. 

To contribute to this project you have to fork it to your account, clone it to your local directory, commit and push changes and then open a PR requests. That's the contribution flow you got to stick in order to get your changes merged.

**Comment by jamesls** [comment]
Thanks for helping out!

Sounds like the next steps for this issues are all set.  I'm going to go ahead and close out this issue.  Let us know if there's anything else we can help with.

**Comment by ferozed** [comment]
Yeah, I have one question. When will my pull request be merged into main tree?
