### ISSUE TITLE
he parameter groupName cannot be used with the parameter subnet . again

### ISSUE THREAD

**Issue by adhorn** [boto/boto#350]
Hi, using HEAD, and having checked  Issue 526:  VPC 2.0: The parameter groupName cannot be used with the parameter subnet.

I still get the same error: 

> > conn = boto.connect_vpc(aws_access_key_id=
> >              AWS_ACCESS_KEY_ID,aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
> > 
> > res = conn.run_instances(AMI_ID,
> > ...                                                      instance_type = 'm1.xlarge',
> > ...                                                      key_name = 'AWSEC2key',
> > ...                                                      min_count = 1, max_count = 1,
> > ...                                                      security_groups=['lm'],
> > ...                                                      user_data = None, 
> > ...                                                      subnet_id = 'subnet_f03c1f99',
> > ...                                                      private_ip_address='10.0.0.189',
> > ...                                                      security_group_ids=['sg-2c342940'],
> > ...                                                      )

Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/Library/Python/2.6/site-packages/boto-2.0-py2.6.egg/boto/ec2/connection.py", line 625, in run_instances
    return self.get_object('RunInstances', params, Reservation, verb='POST')
  File "/Library/Python/2.6/site-packages/boto-2.0-py2.6.egg/boto/connection.py", line 871, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>The parameter groupName cannot be used with the parameter subnet</Message></Error></Errors><RequestID>0a9bac66-e484-4d87-b4bf-62e845016c7e</RequestID></Response>

**Comment by MatthewRalston** [comment]
yeah Ghost's solution of changing subnet name to subnet id. I also don't understand why this is closed..

**Comment by johnhunsley** [comment]
I believe you have created a Security Group without specifying a VPC ID. You have then attempted to create a launch config which launches instances into a subnet within a VPC. Therefore, when it attempts to assign the security group to those instances it fails because it expects the security group ID rather than the name.

From the CloudFormation LaunchConfig spec' -

_"A list that contains the EC2 security groups to assign to the Amazon EC2 instances in the Auto Scaling group. The list can contain the name of existing EC2 security groups or references to AWS::EC2::SecurityGroup resources created in the template. **If your instances are launched within VPC, specify Amazon VPC security group IDs**."_
