### ISSUE TITLE
build_auth_path breaks if bucket is None

### ISSUE THREAD

**Issue by navyad** [boto/boto#3512]
https://github.com/boto/boto/blob/develop/boto/s3/connection.py#L94

breaks if ```bucket``` is None.

  File "/home/naveen/boto/s3/connection.py", line 652, in make_request
    auth_path = self.calling_format.build_auth_path(bucket, key)
  File "/home/naveen/boto/s3/connection.py", line 94, in build_auth_path
    path = '/' + bucket
TypeError: cannot concatenate 'str' and 'NoneType' objects

What could be expected behaviour in case if ```bucket``` is None ?

**Comment by JordonPhillips** [comment]
Bucket cannot be `None`. That code is building a connection to a bucket, so passing `None` in as the bucket doesn't make much sense. Could you provide a code snippet that shows how it gets set that way?

**Comment by StephenChan** [comment]
Not really requesting a reopen, but just providing more info:

One possibility is that you have a Django project using the [django-storages](https://github.com/jschneier/django-storages) app, and you forgot to specify the `AWS_STORAGE_BUCKET_NAME` setting that the app expects. This makes [`S3BotoStorage.__init__()`](https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py) set its bucket attribute to None, and that finally hits the concatenation error when django-storages calls boto for something (the OP's example, or a `listdir`, etc.).

I think the only possible expectation here is that the error message could be more clear (e.g. "`bucket` must be a string"), but the responsibility could just as well be on django-storages instead of boto; and input checking vs. keeping code clean is always a tradeoff.
